// angular/src/app/select-number/select-number.component.ts
import { Component, OnInit, OnDestroy, Input } from '@angular/core';
import { SudokuService, SudokuEvent } from "../sudoku.service";
import { EventListener } from "../events";
import {InformationService} from "../information.service";

@Component({
  selector: 'select-number',
  templateUrl: './select-number.component.html',
  styleUrls: ['./select-number.component.css']
})
export class SelectNumberComponent implements OnInit, OnDestroy, EventListener<SudokuEvent> {

  constructor(private sudokuService:SudokuService,
              private infoService:InformationService) {}

  ngOnInit() {
    console.log("onInit() select-number");
    this.sudokuService.events.register(this);
  }
  ngOnDestroy() {
    this.sudokuService.events.unregister(this);
  } 
  // Handle SudokuService events
  onEvent(e:SudokuEvent, data:Object) {
    switch(e) {
      case SudokuEvent.CELL_SELECTED:
        this.show(data as number);
        break;
      case SudokuEvent.CELL_DESELECTED:
        this.hide();
        break;
    }
  }
  onSelectValue(e:Event) {
    const target = e.target as HTMLElement;
    const number = parseInt(target.innerText) || 0;
    if(number==0) return;

    this.sudokuService.updateCellValue(number);
  }
  onSelectScratch(e:Event) {
    const target = e.target as HTMLElement;
    const number = parseInt(target.innerText) || 0;
    if(number==0) return;

    this.sudokuService.updateCellScratch(number);
  }
  private show(pos:number) {
    // position the select-number element
    const ns = document.getElementById("select-number")!;
    ns.style.display = "grid";

    // hide values that don't make sense
    document.querySelectorAll(".lowlight")
            .forEach(e=>e.classList.remove("lowlight"));

    const scratch = this.sudokuService.board.get(pos).scratch;
    const values  = this.sudokuService.board.getBoxValues(this.sudokuService.board.getBoxIndex(pos));
    const uiSel = document.getElementById("selection")!;
    const uiScr = document.getElementById("scratch")!;
    for(let i=0; i<9; i++) {
        if(scratch.includes(i+1) || values.includes(i+1)) {
            uiScr.children[i].classList.add("lowlight");
        }
        if(values.includes(i+1)) {
            uiSel.children[i].classList.add("lowlight");
        }
    }
  }
  private hide() {
    const ns = document.getElementById("select-number")!;
    ns.style.display = "none";
  }

  /*
  private numberListener(e:Event) {

    const target = e.target as HTMLElement;
    const number = parseInt(target.innerText) || 0;
    if(number==0) return;
    const isScratch = "scratch"==(target.parentNode as HTMLElement).id;
    const i = sudoku.selectedCellIndex || 0;
    const c = sudoku.board.get(i);

    if(isScratch) {
        // Toggle the scratch number
        if(c.scratch.includes(number)) {
            c.scratch.remove(number);
        } else {
            c.scratch.push(number);
        }
        c.scratch.sort();
    } else {
        // Set the cell number
        if(c.isUser) {
            if(c.value==number) {
                // remove the set value
                c.value = 0;
            } else {
                c.value = number;
                c.scratch = [];

                // remove scratch from other affected cells
                this.board.getAffectedCells(i)
                          .forEach((v,i)=>{
                              if(v.scratch.remove(number)) {
                                  this.updateCellUI(v.index);
                              }
                          });
            }
            this.setErrorCells();
        }
    }
    this.updateCellUI(i);
    this.hideNumberSelector();
    this.board.save();
  }
  */
}

<div id="select-number">
    <div id="selection" (click)="onSelectValue($event)">
        <p>1</p>
        <p>2</p>
        <p>3</p>
        <p>4</p>
        <p>5</p>
        <p>6</p>
        <p>7</p>
        <p>8</p>
        <p>9</p>
    </div>
    <div id="scratch" (click)="onSelectScratch($event)">
        <p>1</p>
        <p>2</p>
        <p>3</p>
        <p>4</p>
        <p>5</p>
        <p>6</p>
        <p>7</p>
        <p>8</p>
        <p>9</p>
    </div>
</div>

// reactjs/src/sudoku-components/SelectNumber.js
import React, { Component } from 'react'
import { connect } from "react-redux";
import { setValue, setScratch, setSelectedCell } from './redux/actions'
import "./SelectNumber.css";

class SelectNumber extends Component {

    render() {
        const fragment = (
            <React.Fragment>
                <div id="selection" onClick={this._valueClicked}>
                    <p>1</p>
                    <p>2</p>
                    <p>3</p>
                    <p>4</p>
                    <p>5</p>
                    <p>6</p>
                    <p>7</p>
                    <p>8</p>
                    <p>9</p>
                </div>
                <div id="scratch" onClick={this._scratchClicked}>
                    <p>1</p>
                    <p>2</p>
                    <p>3</p>
                    <p>4</p>
                    <p>5</p>
                    <p>6</p>
                    <p>7</p>
                    <p>8</p>
                    <p>9</p>
                </div>
            </React.Fragment>
        );
        const isSelectable = this.props.selectedCell !== null;
        const className = isSelectable ? "selectable" : "";
        return (
            <div id="select-number" className={className}>
                {isSelectable ? fragment : ""}
            </div>
        )
    }
    componentDidUpdate(prevProps, prevState) {
        if(this.props.selectedCell) {

            /** hide values that don't make sense */
            document.querySelectorAll(".lowlight")
                .forEach(e => e.classList.remove("lowlight"));

            /** Todo */
            const pos = this.props.selectedCell;
            const box = this.props.getBoxIndex(pos);
            const cell = this.props.cells[pos];
            console.assert(cell);

            const scratch = cell.scratch;
            const values = this.props.getBoxValues(box);

            const uiSel = document.getElementById("selection");
            const uiScr = document.getElementById("scratch");
            for(let i = 0; i < 9; i++) {
                if(scratch.includes(i + 1) || values.includes(i + 1)) {
                    uiScr.children[i].classList.add("lowlight");
                }
                if(values.includes(i + 1)) {
                    uiSel.children[i].classList.add("lowlight");
                }
            }
        }
    }

    _valueClicked = (e) => {
        const value = e.target.innerText;
        if(value.length === 1) {
            this.props.dispatch(setValue(this.props.selectedCell, +value));
            this.props.dispatch(setSelectedCell(null));
        }
    }
    _scratchClicked = (e) => {
        const scratch = e.target.innerText;
        if(scratch.length === 1) {
            this.props.dispatch(setScratch(this.props.selectedCell, +scratch));
        }
    }
}

const mapStateToProps = (state) => {
    return state;
};

export default connect(mapStateToProps)(SelectNumber);
